### PR TITLE
fix Safari 9 bug where const is not allowed in strict mode

### PR DESCRIPTION
**Pull request by fadomire**

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for your contribution!

However, I really don't want stick to ES5. ES2015 has been released 4 years ago. Please use a transpiler if needed.

**Comment by mysticatea** [comment]
I apologize. I had misunderstood this PR.

**Comment by fadomire** [comment]
no problem, this PR just affect the UMD build in the case where it fallback to global.
i think that as the UMD build already transpile, it makes sense to replace the unique ```const``` declaration present in the outro

but up to you to

thanks for the project by the way, it works great

**Comment by fadomire** [comment]
Thanks, do you think it is possible to publish it on NPM ?

**Comment by mysticatea** [comment]
Sure, I have done: https://github.com/mysticatea/event-target-shim/releases/tag/v5.0.1

Thank you!

**Pull request merged**
