### PR TITLE
Use babel in all compilation instances

### PR DESCRIPTION
**Pull request by GeorgeTaveras1231**
This fixes a consumer issue where consumers targeting older browsers need to use babel to compile this package

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for your PR. But I will not transpile this package for legacy tools. ES2015 has been published 4 years ago.

**Comment by GeorgeTaveras1231** [comment]
@mysticatea I suppose I understand your point but it seems contradictory because you are using babel for the `umd` compilation. It would make sense to keep a consistent runtime target between all distributions.

Nonetheless, thank you for your time, I will go ahead and use my fork of this repo.

**Comment by mysticatea** [comment]
UMD version is not intended to be used with bundlers. It's for an old-fashioned manner; `<script>` tags.

On the other hand, `.js` and `.mjs` versions are intended to be used with bundlers. It has some preprocess phases before to use in browsers, and we can convert the code for some purpose.

Now, transpiling for ES5 has cost. To express modern syntax with ES5 requires several helper functions. If libraries were transpiled, every library has the helper functions and those will be duplicate in your app. It's really bad. If you transpile your app along with libraries, your bundler would make the helpers only once. If you didn't mind old browsers, you don't need the cost.

**Comment by GeorgeTaveras1231** [comment]
@mysticatea I understand the problem you are describing but the solution to omit any transpilation is not great. As a consumer, it's probably manageable with 1 dependency but in a scenario where you have 10 untranspiled dependencies (each using different ES features), as a consumer you would need to maintain an inventory of all ES features used by your dependencies in order to properly compile them, and would lead to a lot of complexity in your configurations. This problem is compounded if this pattern is adopted by other library authors (my case) where consumers would need to not only know about the runtime target of my libraries, but also the runtime target of the dependencies of my libraries. 

There is a solution built into the rollup babel plugin for the problem you are describing, regarding the es6-to-es5 helpers. If you pass the `runtimeHelpers: true` option:

```js
babel({
  // Rest is omitted
  runtimeHelpers: true
})
```

Babel will import the helper functions from a library named `@babel/runtime` (instead of embedding them in your bundle) which if used consistently by library developers, leads to re-use of the helper libraries in the consuming apps.

**Comment by mysticatea** [comment]
All users don't use babel because other transpilers exist. Anyway, I don't accept transpiling of this package.

**Comment by GeorgeTaveras1231** [comment]
I agree that not all users target ES5 environments. But ES5 sure works in every environment. I doubt that by compiling to ES5 this library will have a significant negative impact on consumers. Also, using the `runtimeHelpers` option doesn't force consumers to use babel as a transpiler, it just adds a runtime dependency on `@babel/runtime`. 

Nonetheless, I respect your decision to force consumers to compile your library. And you may as well close #11 per this decision.

**Pull request closed without merging**
